// ─── Tipo compartido de Photo ─────────────────────────────────────
export interface Photo {
  id: number;
  url: string;
  title: string;
  quote: string;
  storage_path?: string | null;  // ruta interna en Supabase Storage (para poder eliminar)
  created_at?: string | null;
}

// ─── Nombre de la tabla en Supabase ──────────────────────────────
export const PHOTOS_TABLE = "galaxy_photos";

// ─── SQL para crear la tabla (ejecutar en el SQL Editor de Supabase) ─
// Guardado acá como referencia; NO se ejecuta desde el frontend.
//
// create table public.galaxy_photos (
//   id          bigint generated by default as identity primary key,
//   url         text        not null,
//   title       text        not null,
//   quote       text        not null,
//   storage_path text,
//   created_at  timestamptz default now()
// );
//
// -- Habilitar acceso público de lectura
// alter table public.galaxy_photos enable row level security;
//
// create policy "Lectura pública"
//   on public.galaxy_photos for select
//   using (true);
//
// create policy "Solo admin puede insertar"
//   on public.galaxy_photos for insert
//   with check (true);          -- Puedes restringir con auth.uid() si usas auth
//
// create policy "Solo admin puede eliminar"
//   on public.galaxy_photos for delete
//   using (true);
